# Generated by Django 4.2.3 on 2023-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('dec', models.TextField()),
            ],
        ),
    ]
