# Generated by Django 4.2.3 on 2023-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=200)),
                ('d', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
